platform :ios, '13.0'

target 'NFCTagApp' do
  # Pods for NFCTagApp
  
  # Firebase for Cloud Messaging and Remote Config
  pod 'Firebase/Messaging', '~> 10.0'
  pod 'Firebase/RemoteConfig', '~> 10.0'
  pod 'Firebase/Analytics', '~> 10.0'
  
  # Networking
  pod 'Alamofire', '~> 5.7'
  
  # Local storage
  pod 'Realm', '~> 10.40'
  
  target 'NFCTagAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Post-install script to handle build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'FIREBASE_ANALYTICS_COLLECTION_ENABLED=1'
      ]
    end
  end
end
